// Generated by gencpp from file roscopter_msgs/AddWaypoint.msg
// DO NOT EDIT!


#ifndef ROSCOPTER_MSGS_MESSAGE_ADDWAYPOINT_H
#define ROSCOPTER_MSGS_MESSAGE_ADDWAYPOINT_H

#include <ros/service_traits.h>


#include <roscopter_msgs/AddWaypointRequest.h>
#include <roscopter_msgs/AddWaypointResponse.h>


namespace roscopter_msgs
{

struct AddWaypoint
{

typedef AddWaypointRequest Request;
typedef AddWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddWaypoint
} // namespace roscopter_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roscopter_msgs::AddWaypoint > {
  static const char* value()
  {
    return "7cfdc1b052a1b4a9bf3df9443ff04be6";
  }

  static const char* value(const ::roscopter_msgs::AddWaypoint&) { return value(); }
};

template<>
struct DataType< ::roscopter_msgs::AddWaypoint > {
  static const char* value()
  {
    return "roscopter_msgs/AddWaypoint";
  }

  static const char* value(const ::roscopter_msgs::AddWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::roscopter_msgs::AddWaypointRequest> should match 
// service_traits::MD5Sum< ::roscopter_msgs::AddWaypoint > 
template<>
struct MD5Sum< ::roscopter_msgs::AddWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roscopter_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::roscopter_msgs::AddWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roscopter_msgs::AddWaypointRequest> should match 
// service_traits::DataType< ::roscopter_msgs::AddWaypoint > 
template<>
struct DataType< ::roscopter_msgs::AddWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::roscopter_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::roscopter_msgs::AddWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roscopter_msgs::AddWaypointResponse> should match 
// service_traits::MD5Sum< ::roscopter_msgs::AddWaypoint > 
template<>
struct MD5Sum< ::roscopter_msgs::AddWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roscopter_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::roscopter_msgs::AddWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roscopter_msgs::AddWaypointResponse> should match 
// service_traits::DataType< ::roscopter_msgs::AddWaypoint > 
template<>
struct DataType< ::roscopter_msgs::AddWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::roscopter_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::roscopter_msgs::AddWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSCOPTER_MSGS_MESSAGE_ADDWAYPOINT_H
