// Generated by gencpp from file roscopter_msgs/AddWaypointResponse.msg
// DO NOT EDIT!


#ifndef ROSCOPTER_MSGS_MESSAGE_ADDWAYPOINTRESPONSE_H
#define ROSCOPTER_MSGS_MESSAGE_ADDWAYPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscopter_msgs
{
template <class ContainerAllocator>
struct AddWaypointResponse_
{
  typedef AddWaypointResponse_<ContainerAllocator> Type;

  AddWaypointResponse_()
    : length(0)  {
    }
  AddWaypointResponse_(const ContainerAllocator& _alloc)
    : length(0)  {
  (void)_alloc;
    }



   typedef int32_t _length_type;
  _length_type length;





  typedef boost::shared_ptr< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddWaypointResponse_

typedef ::roscopter_msgs::AddWaypointResponse_<std::allocator<void> > AddWaypointResponse;

typedef boost::shared_ptr< ::roscopter_msgs::AddWaypointResponse > AddWaypointResponsePtr;
typedef boost::shared_ptr< ::roscopter_msgs::AddWaypointResponse const> AddWaypointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscopter_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f815b7d03bf050cdebde4eab45424862";
  }

  static const char* value(const ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf815b7d03bf050cdULL;
  static const uint64_t static_value2 = 0xebde4eab45424862ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscopter_msgs/AddWaypointResponse";
  }

  static const char* value(const ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 length\n\
\n\
";
  }

  static const char* value(const ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddWaypointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscopter_msgs::AddWaypointResponse_<ContainerAllocator>& v)
  {
    s << indent << "length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCOPTER_MSGS_MESSAGE_ADDWAYPOINTRESPONSE_H
