// Generated by gencpp from file roscopter_msgs/RemoveWaypoint.msg
// DO NOT EDIT!


#ifndef ROSCOPTER_MSGS_MESSAGE_REMOVEWAYPOINT_H
#define ROSCOPTER_MSGS_MESSAGE_REMOVEWAYPOINT_H

#include <ros/service_traits.h>


#include <roscopter_msgs/RemoveWaypointRequest.h>
#include <roscopter_msgs/RemoveWaypointResponse.h>


namespace roscopter_msgs
{

struct RemoveWaypoint
{

typedef RemoveWaypointRequest Request;
typedef RemoveWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveWaypoint
} // namespace roscopter_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roscopter_msgs::RemoveWaypoint > {
  static const char* value()
  {
    return "8e64718d0fc1826ffd884d37ef95c787";
  }

  static const char* value(const ::roscopter_msgs::RemoveWaypoint&) { return value(); }
};

template<>
struct DataType< ::roscopter_msgs::RemoveWaypoint > {
  static const char* value()
  {
    return "roscopter_msgs/RemoveWaypoint";
  }

  static const char* value(const ::roscopter_msgs::RemoveWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::roscopter_msgs::RemoveWaypointRequest> should match 
// service_traits::MD5Sum< ::roscopter_msgs::RemoveWaypoint > 
template<>
struct MD5Sum< ::roscopter_msgs::RemoveWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roscopter_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::roscopter_msgs::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roscopter_msgs::RemoveWaypointRequest> should match 
// service_traits::DataType< ::roscopter_msgs::RemoveWaypoint > 
template<>
struct DataType< ::roscopter_msgs::RemoveWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::roscopter_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::roscopter_msgs::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roscopter_msgs::RemoveWaypointResponse> should match 
// service_traits::MD5Sum< ::roscopter_msgs::RemoveWaypoint > 
template<>
struct MD5Sum< ::roscopter_msgs::RemoveWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roscopter_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::roscopter_msgs::RemoveWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roscopter_msgs::RemoveWaypointResponse> should match 
// service_traits::DataType< ::roscopter_msgs::RemoveWaypoint > 
template<>
struct DataType< ::roscopter_msgs::RemoveWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::roscopter_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::roscopter_msgs::RemoveWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSCOPTER_MSGS_MESSAGE_REMOVEWAYPOINT_H
