// Generated by gencpp from file roscopter_msgs/SetWaypointsFromFileRequest.msg
// DO NOT EDIT!


#ifndef ROSCOPTER_MSGS_MESSAGE_SETWAYPOINTSFROMFILEREQUEST_H
#define ROSCOPTER_MSGS_MESSAGE_SETWAYPOINTSFROMFILEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscopter_msgs
{
template <class ContainerAllocator>
struct SetWaypointsFromFileRequest_
{
  typedef SetWaypointsFromFileRequest_<ContainerAllocator> Type;

  SetWaypointsFromFileRequest_()
    : filename()  {
    }
  SetWaypointsFromFileRequest_(const ContainerAllocator& _alloc)
    : filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetWaypointsFromFileRequest_

typedef ::roscopter_msgs::SetWaypointsFromFileRequest_<std::allocator<void> > SetWaypointsFromFileRequest;

typedef boost::shared_ptr< ::roscopter_msgs::SetWaypointsFromFileRequest > SetWaypointsFromFileRequestPtr;
typedef boost::shared_ptr< ::roscopter_msgs::SetWaypointsFromFileRequest const> SetWaypointsFromFileRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscopter_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x030824f52a0628eaULL;
  static const uint64_t static_value2 = 0xd956fb9d67e66ae9ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscopter_msgs/SetWaypointsFromFileRequest";
  }

  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
string filename\n\
";
  }

  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetWaypointsFromFileRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscopter_msgs::SetWaypointsFromFileRequest_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCOPTER_MSGS_MESSAGE_SETWAYPOINTSFROMFILEREQUEST_H
