// Generated by gencpp from file roscopter_msgs/SetWaypointsFromFile.msg
// DO NOT EDIT!


#ifndef ROSCOPTER_MSGS_MESSAGE_SETWAYPOINTSFROMFILE_H
#define ROSCOPTER_MSGS_MESSAGE_SETWAYPOINTSFROMFILE_H

#include <ros/service_traits.h>


#include <roscopter_msgs/SetWaypointsFromFileRequest.h>
#include <roscopter_msgs/SetWaypointsFromFileResponse.h>


namespace roscopter_msgs
{

struct SetWaypointsFromFile
{

typedef SetWaypointsFromFileRequest Request;
typedef SetWaypointsFromFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWaypointsFromFile
} // namespace roscopter_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roscopter_msgs::SetWaypointsFromFile > {
  static const char* value()
  {
    return "93a4bc4c60dc17e2a69e3fcaaa25d69d";
  }

  static const char* value(const ::roscopter_msgs::SetWaypointsFromFile&) { return value(); }
};

template<>
struct DataType< ::roscopter_msgs::SetWaypointsFromFile > {
  static const char* value()
  {
    return "roscopter_msgs/SetWaypointsFromFile";
  }

  static const char* value(const ::roscopter_msgs::SetWaypointsFromFile&) { return value(); }
};


// service_traits::MD5Sum< ::roscopter_msgs::SetWaypointsFromFileRequest> should match 
// service_traits::MD5Sum< ::roscopter_msgs::SetWaypointsFromFile > 
template<>
struct MD5Sum< ::roscopter_msgs::SetWaypointsFromFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roscopter_msgs::SetWaypointsFromFile >::value();
  }
  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roscopter_msgs::SetWaypointsFromFileRequest> should match 
// service_traits::DataType< ::roscopter_msgs::SetWaypointsFromFile > 
template<>
struct DataType< ::roscopter_msgs::SetWaypointsFromFileRequest>
{
  static const char* value()
  {
    return DataType< ::roscopter_msgs::SetWaypointsFromFile >::value();
  }
  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roscopter_msgs::SetWaypointsFromFileResponse> should match 
// service_traits::MD5Sum< ::roscopter_msgs::SetWaypointsFromFile > 
template<>
struct MD5Sum< ::roscopter_msgs::SetWaypointsFromFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roscopter_msgs::SetWaypointsFromFile >::value();
  }
  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roscopter_msgs::SetWaypointsFromFileResponse> should match 
// service_traits::DataType< ::roscopter_msgs::SetWaypointsFromFile > 
template<>
struct DataType< ::roscopter_msgs::SetWaypointsFromFileResponse>
{
  static const char* value()
  {
    return DataType< ::roscopter_msgs::SetWaypointsFromFile >::value();
  }
  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSCOPTER_MSGS_MESSAGE_SETWAYPOINTSFROMFILE_H
