// Generated by gencpp from file roscopter_msgs/SetWaypointsFromFileResponse.msg
// DO NOT EDIT!


#ifndef ROSCOPTER_MSGS_MESSAGE_SETWAYPOINTSFROMFILERESPONSE_H
#define ROSCOPTER_MSGS_MESSAGE_SETWAYPOINTSFROMFILERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscopter_msgs
{
template <class ContainerAllocator>
struct SetWaypointsFromFileResponse_
{
  typedef SetWaypointsFromFileResponse_<ContainerAllocator> Type;

  SetWaypointsFromFileResponse_()
    : success(false)  {
    }
  SetWaypointsFromFileResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetWaypointsFromFileResponse_

typedef ::roscopter_msgs::SetWaypointsFromFileResponse_<std::allocator<void> > SetWaypointsFromFileResponse;

typedef boost::shared_ptr< ::roscopter_msgs::SetWaypointsFromFileResponse > SetWaypointsFromFileResponsePtr;
typedef boost::shared_ptr< ::roscopter_msgs::SetWaypointsFromFileResponse const> SetWaypointsFromFileResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscopter_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscopter_msgs/SetWaypointsFromFileResponse";
  }

  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetWaypointsFromFileResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscopter_msgs::SetWaypointsFromFileResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCOPTER_MSGS_MESSAGE_SETWAYPOINTSFROMFILERESPONSE_H
