//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the autorally_control package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __autorally_control__PATHINTEGRALPARAMSCONFIG_H__
#define __autorally_control__PATHINTEGRALPARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace autorally_control
{
  class PathIntegralParamsConfigStatics;

  class PathIntegralParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(PathIntegralParamsConfig &config, const PathIntegralParamsConfig &max, const PathIntegralParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PathIntegralParamsConfig &config1, const PathIntegralParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PathIntegralParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PathIntegralParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PathIntegralParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PathIntegralParamsConfig &config) const = 0;
      virtual void getValue(const PathIntegralParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PathIntegralParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (PathIntegralParamsConfig::* field);

      virtual void clamp(PathIntegralParamsConfig &config, const PathIntegralParamsConfig &max, const PathIntegralParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PathIntegralParamsConfig &config1, const PathIntegralParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PathIntegralParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PathIntegralParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PathIntegralParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PathIntegralParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PathIntegralParamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PathIntegralParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PathIntegralParamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<PathIntegralParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PathIntegralParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_throttle"==(*_i)->name){max_throttle = boost::any_cast<double>(val);}
        if("desired_speed"==(*_i)->name){desired_speed = boost::any_cast<double>(val);}
        if("speed_coefficient"==(*_i)->name){speed_coefficient = boost::any_cast<double>(val);}
        if("track_coefficient"==(*_i)->name){track_coefficient = boost::any_cast<double>(val);}
        if("max_slip_angle"==(*_i)->name){max_slip_angle = boost::any_cast<double>(val);}
        if("slip_penalty"==(*_i)->name){slip_penalty = boost::any_cast<double>(val);}
        if("crash_coefficient"==(*_i)->name){crash_coefficient = boost::any_cast<double>(val);}
        if("track_slop"==(*_i)->name){track_slop = boost::any_cast<double>(val);}
        if("steering_coeff"==(*_i)->name){steering_coeff = boost::any_cast<double>(val);}
        if("throttle_coeff"==(*_i)->name){throttle_coeff = boost::any_cast<double>(val);}
      }
    }

    double max_throttle;
double desired_speed;
double speed_coefficient;
double track_coefficient;
double max_slip_angle;
double slip_penalty;
double crash_coefficient;
double track_slop;
double steering_coeff;
double throttle_coeff;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_throttle;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double desired_speed;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double speed_coefficient;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double track_coefficient;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_slip_angle;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double slip_penalty;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double crash_coefficient;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double track_slop;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steering_coeff;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double throttle_coeff;
//#line 218 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PathIntegralParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PathIntegralParamsConfig &__max__ = __getMax__();
      const PathIntegralParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PathIntegralParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PathIntegralParamsConfig &__getDefault__();
    static const PathIntegralParamsConfig &__getMax__();
    static const PathIntegralParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PathIntegralParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PathIntegralParamsConfig::ParamDescription<std::string>::clamp(PathIntegralParamsConfig &config, const PathIntegralParamsConfig &max, const PathIntegralParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PathIntegralParamsConfigStatics
  {
    friend class PathIntegralParamsConfig;

    PathIntegralParamsConfigStatics()
    {
PathIntegralParamsConfig::GroupDescription<PathIntegralParamsConfig::DEFAULT, PathIntegralParamsConfig> Default("Default", "", 0, 0, true, &PathIntegralParamsConfig::groups);
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_throttle = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_throttle = 1.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_throttle = 0.65;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("max_throttle", "double", 0, "Maximum applied throttle", "", &PathIntegralParamsConfig::max_throttle)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("max_throttle", "double", 0, "Maximum applied throttle", "", &PathIntegralParamsConfig::max_throttle)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.desired_speed = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.desired_speed = 25.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.desired_speed = 6.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("desired_speed", "double", 0, "Speed Target for the MPPI controller", "", &PathIntegralParamsConfig::desired_speed)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("desired_speed", "double", 0, "Speed Target for the MPPI controller", "", &PathIntegralParamsConfig::desired_speed)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.speed_coefficient = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.speed_coefficient = 20.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.speed_coefficient = 4.25;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("speed_coefficient", "double", 0, "Weight for acheiving target velocity", "", &PathIntegralParamsConfig::speed_coefficient)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("speed_coefficient", "double", 0, "Weight for acheiving target velocity", "", &PathIntegralParamsConfig::speed_coefficient)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.track_coefficient = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.track_coefficient = 500.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.track_coefficient = 200.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("track_coefficient", "double", 0, "Weight for staying on the track", "", &PathIntegralParamsConfig::track_coefficient)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("track_coefficient", "double", 0, "Weight for staying on the track", "", &PathIntegralParamsConfig::track_coefficient)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_slip_angle = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_slip_angle = 3.14;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_slip_angle = 1.25;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("max_slip_angle", "double", 0, "Maximum slip angle allowed", "", &PathIntegralParamsConfig::max_slip_angle)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("max_slip_angle", "double", 0, "Maximum slip angle allowed", "", &PathIntegralParamsConfig::max_slip_angle)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.slip_penalty = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.slip_penalty = 1000.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.slip_penalty = 10.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("slip_penalty", "double", 0, "Penalty for violating slip angle threshold", "", &PathIntegralParamsConfig::slip_penalty)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("slip_penalty", "double", 0, "Penalty for violating slip angle threshold", "", &PathIntegralParamsConfig::slip_penalty)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.crash_coefficient = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.crash_coefficient = 20000.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.crash_coefficient = 10000.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("crash_coefficient", "double", 0, "Penalty for crashing", "", &PathIntegralParamsConfig::crash_coefficient)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("crash_coefficient", "double", 0, "Penalty for crashing", "", &PathIntegralParamsConfig::crash_coefficient)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.track_slop = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.track_slop = 0.75;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.track_slop = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("track_slop", "double", 0, "Value for clipping track cost to zero.", "", &PathIntegralParamsConfig::track_slop)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("track_slop", "double", 0, "Value for clipping track cost to zero.", "", &PathIntegralParamsConfig::track_slop)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steering_coeff = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steering_coeff = 1.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steering_coeff = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("steering_coeff", "double", 0, "Steering Cost Coefficient", "", &PathIntegralParamsConfig::steering_coeff)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("steering_coeff", "double", 0, "Steering Cost Coefficient", "", &PathIntegralParamsConfig::steering_coeff)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.throttle_coeff = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.throttle_coeff = 1.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.throttle_coeff = 0.0;
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("throttle_coeff", "double", 0, "Throttle Cost Coefficient", "", &PathIntegralParamsConfig::throttle_coeff)));
//#line 292 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathIntegralParamsConfig::AbstractParamDescriptionConstPtr(new PathIntegralParamsConfig::ParamDescription<double>("throttle_coeff", "double", 0, "Throttle Cost Coefficient", "", &PathIntegralParamsConfig::throttle_coeff)));
//#line 245 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PathIntegralParamsConfig::AbstractGroupDescriptionConstPtr(new PathIntegralParamsConfig::GroupDescription<PathIntegralParamsConfig::DEFAULT, PathIntegralParamsConfig>(Default)));
//#line 356 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PathIntegralParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PathIntegralParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PathIntegralParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PathIntegralParamsConfig __max__;
    PathIntegralParamsConfig __min__;
    PathIntegralParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PathIntegralParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PathIntegralParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PathIntegralParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PathIntegralParamsConfig &PathIntegralParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PathIntegralParamsConfig &PathIntegralParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PathIntegralParamsConfig &PathIntegralParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PathIntegralParamsConfig::AbstractParamDescriptionConstPtr> &PathIntegralParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PathIntegralParamsConfig::AbstractGroupDescriptionConstPtr> &PathIntegralParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PathIntegralParamsConfigStatics *PathIntegralParamsConfig::__get_statics__()
  {
    const static PathIntegralParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PathIntegralParamsConfigStatics::get_instance();

    return statics;
  }


}

#endif // __PATHINTEGRALPARAMSRECONFIGURATOR_H__
