debug: 3                    # Range 0-4 (0 means no debug statements will print)

device: /dev/USBgps

frame_id: gps
dynamic_model: 0
fix_mode: 2              # Switches between 2D/3D automatically
dr_limit: 0                 # Dead reckoning limit
enable_ppp: false           # Advanced setting not supported by all devices

rate: 1                     # Measurement rate in Hz
nav_rate: 1                 # in number of measurement cycles
tmode3: 0

uart1:
  baudrate: 9600           # baudrate is device specific, check the device manual
  in: 7                     # UBX
  out: 3                    # RTCM

# RTCM out config
#rtcm:
#  ids: [5, 87, 77, 230]     # RTCM Messages to configure
#  rates: [1, 1, 1, 10]      # Rates of RTCM messages above,
                            # in number of navigation solutions
dat:
  set: false                # Do not set the user configured datum

# GNSS Config, verify which GNSS are supported by your device
gnss:
  gps: true                 # (not required since it defaults to true)
  glonass: false
  beidou: false
  qzss: false
  sbas: false

inf:
  all: true                   # Whether to display INF messages

# Message subscriptions
subscribe:
  all: true                 # Subscribe to all messages
  aid:
    all: false                # ... except AID messages

# Enable u-blox message publishers
publish:
  all: true

