(cl:defpackage roscopter_msgs-srv
  (:use )
  (:export
   "ADDWAYPOINT"
   "<ADDWAYPOINT-REQUEST>"
   "ADDWAYPOINT-REQUEST"
   "<ADDWAYPOINT-RESPONSE>"
   "ADDWAYPOINT-RESPONSE"
   "REMOVEWAYPOINT"
   "<REMOVEWAYPOINT-REQUEST>"
   "REMOVEWAYPOINT-REQUEST"
   "<REMOVEWAYPOINT-RESPONSE>"
   "REMOVEWAYPOINT-RESPONSE"
   "SETWAYPOINTSFROMFILE"
   "<SETWAYPOINTSFROMFILE-REQUEST>"
   "SETWAYPOINTSFROMFILE-REQUEST"
   "<SETWAYPOINTSFROMFILE-RESPONSE>"
   "SETWAYPOINTSFROMFILE-RESPONSE"
  ))

