(cl:in-package fcu_common-msg)
(cl:export '(POSITION-VAL
          POSITION
          VA-VAL
          VA
          ALPHA-VAL
          ALPHA
          BETA-VAL
          BETA
          PHI-VAL
          PHI
          THETA-VAL
          THETA
          PSI-VAL
          PSI
          CHI-VAL
          CHI
          P-VAL
          P
          Q-VAL
          Q
          R-VAL
          R
          VG-VAL
          VG
          WN-VAL
          WN
          WE-VAL
          WE
          QUAT-VAL
          QUAT
          QUAT_VALID-VAL
          QUAT_VALID
          CHI_DEG-VAL
          CHI_DEG
          PSI_DEG-VAL
          PSI_DEG
))