dist: "trusty"
language: cpp

addons:
  apt:
    packages:
      - build-essential
      - libc6-i386
      - lib32bz2-1.0
      - lib32ncurses5
      - lib32z1
      - cmake
      - libgtest-dev
      - libeigen3-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt update -qq  
  - gcc --version
  - curl --retry 10 --retry-max-time 120 -L "https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q1-update/+download/gcc-arm-none-eabi-5_3-2016q1-20160330-linux.tar.bz2" | tar xfj -

install:
  - sudo apt-get install -qq g++-5 gcc-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_3-2016q1/bin
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make 
  - sudo cp *.a /usr/lib

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - arm-none-eabi-gcc --version

script:
  - ./run_tests.sh

