site_name: ROSflight
site_url: http://rosflight.org
repo_url: https://github.com/rosflight/firmware
edit_uri: blob/master/docs/
google_analytics: ['UA-96018590-2', 'docs.rosflight.org']
theme: readthedocs
theme_dir: docs/custom_theme
extra_css: [custom_theme/extra.css]
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
pages:
  - Home: index.md
  - User Guide:
    - Getting started: user-guide/getting-started.md
    - Hardware setup: user-guide/hardware-setup.md
    - Autopilot setup: user-guide/autopilot-setup.md
    - RC Configuration: user-guide/rc-configuration.md
    - ROS setup: user-guide/ros-setup.md
    - Parameter Configuration: user-guide/parameter-configuration.md
    - Preflight checks: user-guide/preflight-checks.md
    - Improving performance: user-guide/performance.md
    - Running Gazebo Simulation: user-guide/gazebo_simulation.md
    - Autonomous flight: user-guide/autonomous-flight.md
  - Developer Guide:
    - Contribution Guidelines: developer-guide/contribution-guidelines.md
    - Style Guide: developer-guide/style-guide.md
    - Code Architecture: developer-guide/code-architecture.md
    - Building and Flashing: developer-guide/building-flashing.md
    - Using a Debugger: developer-guide/debugging.md
    - Writing Documentation: developer-guide/writing-documentation.md
